# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notes.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'notes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotes.proto\x12\x05notes\"2\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"3\n\x11\x43reateNoteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1c\n\x0eGetNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x12\n\x10ListNotesRequest\"?\n\x11UpdateNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1f\n\x11\x44\x65leteNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x0cNoteResponse\x12\x19\n\x04note\x18\x01 \x01(\x0b\x32\x0b.notes.Note\"/\n\x11ListNotesResponse\x12\x1a\n\x05notes\x18\x01 \x03(\x0b\x32\x0b.notes.Note\"%\n\x12\x44\x65leteNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc1\x02\n\x0bNoteService\x12;\n\nCreateNote\x12\x18.notes.CreateNoteRequest\x1a\x13.notes.NoteResponse\x12\x35\n\x07GetNote\x12\x15.notes.GetNoteRequest\x1a\x13.notes.NoteResponse\x12>\n\tListNotes\x12\x17.notes.ListNotesRequest\x1a\x18.notes.ListNotesResponse\x12;\n\nUpdateNote\x12\x18.notes.UpdateNoteRequest\x1a\x13.notes.NoteResponse\x12\x41\n\nDeleteNote\x12\x18.notes.DeleteNoteRequest\x1a\x19.notes.DeleteNoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=22
  _globals['_NOTE']._serialized_end=72
  _globals['_CREATENOTEREQUEST']._serialized_start=74
  _globals['_CREATENOTEREQUEST']._serialized_end=125
  _globals['_GETNOTEREQUEST']._serialized_start=127
  _globals['_GETNOTEREQUEST']._serialized_end=155
  _globals['_LISTNOTESREQUEST']._serialized_start=157
  _globals['_LISTNOTESREQUEST']._serialized_end=175
  _globals['_UPDATENOTEREQUEST']._serialized_start=177
  _globals['_UPDATENOTEREQUEST']._serialized_end=240
  _globals['_DELETENOTEREQUEST']._serialized_start=242
  _globals['_DELETENOTEREQUEST']._serialized_end=273
  _globals['_NOTERESPONSE']._serialized_start=275
  _globals['_NOTERESPONSE']._serialized_end=316
  _globals['_LISTNOTESRESPONSE']._serialized_start=318
  _globals['_LISTNOTESRESPONSE']._serialized_end=365
  _globals['_DELETENOTERESPONSE']._serialized_start=367
  _globals['_DELETENOTERESPONSE']._serialized_end=404
  _globals['_NOTESERVICE']._serialized_start=407
  _globals['_NOTESERVICE']._serialized_end=728
# @@protoc_insertion_point(module_scope)
